# Generated by Django 3.2.9 on 2021-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='app1/gallery/imgs')),
                ('caption', models.CharField(default='', max_length=400, verbose_name='caption')),
            ],
        ),
    ]
