# Generated by Django 3.2.9 on 2021-12-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediaimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='app1/gallery/imgs')),
                ('caption', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='caption')),
            ],
        ),
    ]
