# Generated by Django 3.2.9 on 2021-12-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_mediaimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='app1/media/imgs')),
                ('caption', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='caption')),
            ],
        ),
        migrations.AlterField(
            model_name='mediaimg',
            name='img',
            field=models.ImageField(default='', upload_to='app1/media/imgs'),
        ),
    ]
