# Generated by Django 3.2.9 on 2021-12-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='registration',
            name='case',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='ce',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='co',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='contact',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='el',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='et',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_instalment',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_loan',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_pcm',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='me',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='mission_branch',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='other_i_branch',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='wp',
            field=models.CharField(default='', max_length=150),
        ),
    ]
