# Generated by Django 3.2.9 on 2021-12-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20211228_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='other_i_branch',
            new_name='other_interasted_branches',
        ),
    ]
