# Generated by Django 3.2.9 on 2021-12-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_other_i_branch_registration_other_interasted_branches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='case',
            new_name='cast',
        ),
    ]
