# Generated by Django 3.2.9 on 2021-12-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_case_registration_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='ce',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='co',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='el',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='et',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='me',
        ),
        migrations.AlterField(
            model_name='registration',
            name='other_interasted_branches',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
