# Generated by Django 3.2.9 on 2021-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20211229_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
