# Generated by Django 3.2.9 on 2022-01-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='ttl',
        ),
    ]
