# Generated by Django 4.0.4 on 2022-05-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_contact_alter_registration_cast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('wfrom', models.CharField(max_length=200)),
                ('cmt', models.TextField()),
            ],
        ),
    ]
