# Generated by Django 4.0.4 on 2022-05-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_rename_mobile_feedback_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
    ]
