# Generated by Django 4.0.6 on 2022-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_feedback_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='app1/gallery/imgs')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
