# Generated by Django 4.1 on 2022-08-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_pop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou',
            name='logo',
            field=models.ImageField(blank=True, default='app1/media/imgs/blank_P9xJb40.png', null=True, upload_to='images/mou/logo'),
        ),
    ]
