# Generated by Django 4.1.2 on 2022-11-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_mou_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='img',
            field=models.ImageField(default='', upload_to='app1/pop/imgs'),
        ),
    ]
