# Generated by Django 4.1.2 on 2023-02-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_pop_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('yop', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('maritalstaus', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('aftergraduation', models.TextField()),
                ('memorie', models.TextField()),
            ],
        ),
    ]
